# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- script: |
    git config --global user.email "test@test.com"
    git config --global user.name "Azure pipeline"
    git remote add heroku https://heroku:$(pat)@git.heroku.com/testowa-x.git
    git add .
    git commit -m "temp commit for deployment"
    git push -f heroku master
  displayName: 'Deploy to heroku'